# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: users_rails
  password: fcehd84efer6

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: users_rails
  password: fcehd84efer6

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
  username: users_rails
  password: fcehd84efer6

